### ISSUE TITLE
Some app suggestions

### ISSUE THREAD

**Issue by osering** [wacko1805/Fossapps-creator#1]
Hello!
Great idea to use Magisk in such a way!

I would suggest following additions:

Email client:
{   
          "name": "SimpleEmail",
          "url": "https://f-droid.org/repo/org.dystopia.email_116.apk",
          "moreinfo": "https://f-droid.org/en/packages/org.dystopia.email/"

} 

Music players:

{   
          "name": "AntennaPod",
          "url": "https://f-droid.org/repo/de.danoeh.antennapod_2040095.apk",
          "moreinfo": "https://f-droid.org/en/packages/de.danoeh.antennapod/"

} 
{   
          "name": "Auxio",
          "url": "https://f-droid.org/repo/org.oxycblt.auxio_8.apk",
          "moreinfo": "https://f-droid.org/en/packages/org.oxycblt.auxio/"

} 
{   
          "name": "Voice - Audiobook Player",
          "url": "https://f-droid.org/repo/de.ph1b.audiobook_3060342.apk",
          "moreinfo": "https://f-droid.org/packages/de.ph1b.audiobook/"

} 

Browsers:
{   
          "name": "DuckDuckGo Privacy Browser",
          "url": "https://f-droid.org/repo/com.duckduckgo.mobile.android_51023000.apk",
          "moreinfo": "https://f-droid.org/en/packages/com.duckduckgo.mobile.android/"

} 
{   
          "name": "Fennec",
          "url": "https://f-droid.org/repo/org.mozilla.fennec_fdroid_941120.apk",
          "moreinfo": "https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/"

} 

If messengers "group" planned: Element, Signal-Foss (not included in F-droid, but can be added from https://www.twinhelix.com › apps › signal-foss) Nekogram, Briar, WhatsApp Web to Go

**Comment by wacko1805** [comment]
Added these apps,
Thanks
https://github.com/wacko1805/Fossapps-creator/commit/02678365d7913103defa3ebb407d6fa88d96f7a2
