### ISSUE TITLE
App Suggestion

### ISSUE THREAD

**Issue by pantsufan** [wacko1805/Fossapps-creator#3]
YouTube App
{
   "name":"NewPipe x SponsorBlock",
   "url":"https://github.com/polymorphicshade/NewPipe/releases/download/v0.21.14/newpipe_x_sponsorblock_0.21.14.apk",
   "moreinfo":"https://github.com/polymorphicshade/NewPipe"
}

**Comment by wacko1805** [comment]
Added. Thanks!

https://github.com/wacko1805/Fossapps-creator/commit/47f877cc2c1402f9e152191a176d756560d75cba
